name: snakey-snakey

on:
  # run on every push to main branch
  push:
    branches:
      - master

  # run automatically once every day
  schedule:
    - cron: "0 0 * * *"

  # allows to run job manually
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: snakey born
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            buidl/snek-light.svg?palette=github-light&color_snake=#ff44cc
            buidl/snek-dark.svg?palette=github-dark&color_snake=#00CED1&color_dots=#1A1A1A,#333333,#4F4F4F,#808080,#A9A9A9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # push the content of <build_dir> to a branch
      # content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> as a github page
      - name: snek slither to page
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: snakeyborn
          build_dir: buidl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
